strongloop/loopback-swagger

README.md

We are about to move swagger-spec generator from loopback-explorer to loopback-swagger. Because loopback-explorer is a regular (fully supported) module, we need to remove loopback-swagger from the Labs mode first.
/to @raymondfeng please review
/cc @crandmck

Remove the Labs label

---

lib/specgen/route-helper.js
lib/specgen/swagger-spec-generator.js
test/specgen/route-helper.test.js
test/specgen/swagger-spec-generator.test.js

At the moment, the operation id is constructed as a remote method name.
However, it is posible to map a single method to multiple HTTP
endpoints (swagger paths)
For example, `PersistedModel.exists` is mapped to both
HEAD /mymodels/{id}
GET /mymodels/{id}/exists
As a result, the generated swagger operation ids are not unique.
This patch fixes the problem by detecting multi-endpoint methods
and appending HTTP verb and path to the name-based operation id.
Using the example above, the following operation ids are generated:
Product.exists__head_Products_{id}
Product.exists__get_Products_{id}_exists
Fix strongloop/loopback-component-explorer#132
/to @raymondfeng please review
/cc @ritch @sclaussen

specgen: ensure operation ids are unique

---

lib/specgen/model-helper.js
lib/specgen/type-registry.js
test/specgen/swagger-spec-generator.test.js

**1. Fix hidden models referenced by hidden models**
By default, loopback apps come with two kinds of hidden models not
exposed via REST API:
1) A private model than can be accessed via relation methods,
for example AccessToken exposed via `/users/:id/accessTokens`
2) A private model referenced by other private models only,
for example Role and RoleModel.
The first kind should be included in swagger definitions, since it's
referenced in accepts/returns arguments of relation methods.
The second kind should be excluded, because it's not referenced at all.
This commit fixes the spec generator to exclude hidden models that are
refereced only by hidden models.
**2. Fix the definition of GeoPoint (introduced in #20) to be a valid Swagger definiton (JSON schema)**
/to @raymondfeng please review …

Fix unused models + GeoPoint definition

---

lib/specgen/schema-builder.js
test/specgen/model-helper.test.js

Connect to https://github.com/strongloop/loopback-swagger/issues/18
@bajtos Please review. Thanks!

Treat property as type 'any' if not specified

---

lib/codegen/generator-v2.js
lib/codegen/model.ejs
test/codegen/pet-expanded.json
test/codegen/swagger-v2.test.js

The PR allows `{id}` and `.` in operationId.

Handle {id} and . in operation id

---

lib/specgen/route-helper.js
test/specgen/route-helper.test.js

The PR removes empty required for the response object. Otherwise, the generated swagger will fail the validation.

Do not generate required if no item is present

---

.gitignore
index.js
intl/en/messages.json
lib/specgen/route-helper.js
lib/specgen/schema-builder.js
lib/specgen/swagger-spec-generator.js
lib/specgen/type-registry.js
package.json

Connect to strongloop/loopback/issues/2422
@0candy, please review.

Globalization

---

lib/specgen/schema-builder.js
test/specgen/schema-builder.test.js

For nested object types, we expose them under the "properties" property
recursively instead of exposing them as an empty plain object ({}).

Expose object types as nested properties

---

lib/specgen/schema-builder.js
test/specgen/route-helper.test.js

Add support for a new remoting metadata property "model". This new
property can be used for arguments of `type: 'object'` to instruct
the swagger-generator to use the provided model as a source of the
argument schema.
Connect to strongloop/loopback#1806
@gunjpan please review
cc @richardpringle

Allow object arguments to provide Model

---

package.json

>IMPORTANT: In LoopBack v3.0, loopback-datasource-juggler is no longer a peer dependency that has to be explicitly listed in app/project package.json. Keep this in mind while creating `loopback-2.x` branches and updating `master` to use `loopback@3`.
* Remove juggler as a dependency
/to: @superkhau 
/cc: @bajtos

Remove juggler as a dependency

---

lib/specgen/route-helper.js
test/specgen/route-helper.test.js

Swagger spec 2.0 supports "formData" instead of "form". This patch fixes
an API explorer bug for KeyValueModel PUT requests not honouring
`accepts.http.source: 'form'` as "formData".
Connect to https://github.com/strongloop/loopback/issues/2770
Also verified API explorer fix for KeyValueModel manually with a locally scaffolded app.
@bajtos PTAL

Coerce form to formData in accepts.http.source

---

lib/specgen/schema-builder.js
test/specgen/schema-builder.test.js

This is due to the Swagger 2.x spec not supporting nulls.
Details: https://github.com/OAI/OpenAPI-Specification/issues/229
strongloop/loopback-component-explorer#146

Omit null default values from schema

---

lib/codegen/spec-converter.js
lib/specgen/route-helper.js
lib/specgen/schema-builder.js
lib/specgen/type-registry.js
test/specgen/route-helper.test.js

Also closes https://github.com/strongloop/loopback-component-explorer/issues/103
Allows `File` type to be turned into a file upload field.
- #34
- https://github.com/strongloop/loopback-component-explorer/issues/103

Add support for file type #34

---

lib/specgen/route-helper.js
lib/specgen/tag-builder.js
test/specgen/route-helper.test.js
test/specgen/swagger-spec-generator.test.js
test/specgen/tag-builder.test.js

PR adds two new features
1. Specify a custom tag to be used for a model in the API explorer via 'tags' array
2. Allow `externalDocs` properties to be set on models.
Rationale:
1. The model name used in the app might not be what you want exposed in the explorer or you may want to use some other heading for various reasons (e.g. give it a prefix)
2. `externalDocs` has been a `TODO` in the code base for a long time.
Current implementation is on the `<model>.json` in the options.swagger property:
MyModel.json:
```json
{
"name": "SomeModel",
"options": {
"swagger": {
"tag": {
"name": "_Models",
"externalDocs": {
"url": "http://my-external-spec.example.com"
}
}
}
}
}
```
Am opening to changing/moving the properties used to define these settings. …

Allow custom model tags and externalDocs

---

lib/specgen/model-helper.js
lib/specgen/schema-builder.js
test/specgen/swagger-spec-generator.test.js

This is part of solution forhttps://github.com/strongloop/loopback/issues/2924
Other PRs involved in the solution of issue https://github.com/strongloop/loopback/issues/2924
- https://github.com/strongloop/loopback-datasource-juggler/pull/1453
- https://github.com/strongloop/loopback/pull/3548
@bajtos Work In Progress PR. Please take a initial look.
This PR changes include
- check for createOnlyInstance in schema-builder.js to use a new model for create only
- defining and setting separate model for create operation based on updateOnly props - changes in model-helper.js
TODO:
Add a test case

Support updateOnly feature

---

lib/specgen/route-helper.js
test/specgen/route-helper.test.js

Per swagger spec, the `required` field for path parameters
must be true
- connect to https://github.com/strongloop-internal/scrum-apex/issues/305

Set required to be true for path parameters

---

lib/specgen/model-helper.js
lib/specgen/route-helper.js
lib/specgen/schema-builder.js
lib/specgen/swagger-spec-generator.js
test/specgen/swagger-spec-generator.test.js

Enable 'updateOnly' feature based on generateOperationScopedModels flag. generateOperationScopedModels is a generated flag in component-config.json which get passed in through options[].

Enable 'updateOnly' feature based on generateOperationScopedModels

---

lib/specgen/route-helper.js
test/specgen/route-helper.test.js

`in: 'form'` was giving the correct input type but wasn't actually sending the file payload to the server. 'formData' fixes this.
- closes #94

Fix file upload attachments

---

lib/codegen/generator-base.js
lib/codegen/model.ejs
test/codegen/pet-with-embedded-schema.json
test/codegen/swagger-v2.test.js

- No separate definitions
- Parameter with `-`
See https://github.com/strongloop/loopback/issues/3688
- connect to <link_to_referenced_issue>

Improve swagger mapping

---

lib/specgen/model-helper.js
lib/specgen/route-helper.js
lib/specgen/schema-builder.js
test/specgen/model-helper.test.js
test/specgen/route-helper.test.js
test/specgen/schema-builder.test.js

Add basic support for examples at the property, model and endpoint level for more rich documentation.
Property:
```json
"properties": {
"name": {
"type": "string",
"example": "Marty McFly"
}
}
```
Model:
```json
"options": {
"swagger": {
"example" : {
"name": "Marty McFly",
"occupation": "Time Traveller"
}
}
}
"properties": {
"...": "..."
}
```
Endpoint:
```javascript
User.remoteMethod('register', {
accepts: {
arg: 'user',
type: 'User',
example: {
name: 'Emmett Brown',
occupation: 'Scientist'
}
}
// ...
})
```

Add support for examples in models and responses

---

lib/codegen/generator-v2.js
lib/codegen/json-schema.js
test/codegen/pet-with-refs.json
test/codegen/swagger-v2.test.js

To use swagger-parser in generator-loopback to deference $ref for
objects, we need to preserve $ref to derive model names
- connect to <link_to_referenced_issue>

Improve support for $ref

---

lib/codegen/spec-converter.js
package.json

Upgraded lodash from v3 to v4
There is an NSP vulnerability warning reported for using lodash below v4 (Ref: https://nodesecurity.io/advisories/577)
These are the compatibility-warnings for upgrading lodash from v3 to v4 (https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings)
I took a quick look at the lodash usage in loopback-swagger 3.x, and these are all the functions:
- _.camelCase
- _.template
- **_.contains** -> **_.includes**
- _.map
- **_.each**
- **_.extend**
- _.isEmpty
- _.clone
- _.includes
- _.defaults
- _.assign
- _.cloneDeep
- _.matchesProperty
- _.property
- _.values
The only changes need here is to replace _.contains with _.includes in `/lib/code-gen/spec-converter.js`
- connect to <https://github.com/strongloop/loopback-swagger/issues/120>

Fix lodash vulnerability: Prototype Pollution

---

lib/specgen/route-helper.js
test/specgen/route-helper.test.js

Fixed the issue where return types not set as a root property were not being set as loopback model references.
- fix #126 
- fix strongloop/loopback#2447

specgen: emit correct non-root return types

---

lib/specgen/model-helper.js
lib/specgen/route-helper.js
package.json
test/codegen/swagger-v2.test.js
test/specgen/route-helper.test.js

The new version of our config enabled function-paren-newline rule, this commit fixes the codebase to use more consistent handling of newlines when calling functions.
See strongloop/eslint-config-loopback#29
/cc @Danwakeem

Upgrade eslint-config-loopback + fix formatting

---

lib/specgen/swagger-spec-generator.js
test/specgen/swagger-spec-generator.test.js

This patch retrieves a project description from package.json
-connect to #122 

specgen: Retrieve description from package.json

---

lib/specgen/route-helper.js
test/specgen/route-helper.test.js

Fix #130 
Filter out the return arguments if the `http.target` is set to `status|header` when converting returns to swagger.
- connect to #130 
- connect to <link_to_referenced_issue>

Fix return arguments which htttp.target is status|header being added to swagger return body

---

lib/codegen/generator-base.js
test/codegen/pet-with-special-names.json
test/codegen/swagger-v2.test.js

Allow tag or param names to contain '-' or spaces

---

lib/specgen/route-helper.js
test/specgen/route-helper.test.js

Before the fix an undefined error message was added to responseMessages when `route.http` was set, but not `route.http.errorStatus`.
- connect to strongloop/strong-remoting#475

Check for route.http.errorStatus before adding it to responseMessages

---

example/generator.js
index.js
lib/codegen/generator-v1.2.js
lib/codegen/model-template.js
lib/codegen/spec-converter.js
lib/specgen/model-helper.js
lib/specgen/route-helper.js
lib/specgen/schema-builder.js
lib/specgen/swagger-spec-generator.js
lib/specgen/tag-builder.js
lib/specgen/type-registry.js
test/specgen/fixtures/dummy-swagger-ui/swagger-ui.js
test/specgen/model-helper.test.js
test/specgen/route-helper.test.js
test/specgen/schema-builder.test.js
test/specgen/swagger-spec-generator.test.js
test/specgen/tag-builder.test.js

Related: strongloop-internal/scrum-apex#440
Update the copyrights year in the rest of the packages besides #4596.
The changes are introduced by running the `slt copyright` command. 
- connect to <link_to_referenced_issue>

chore: update copyright year
