README.md
Add loopback-explorer to the list of modules which are using loopback-swagger
=> README: link to loopback-explorer

lib/specgen/schema-builder.js, test/specgen/schema-builder.test.js
/to @bajtos 
It fixes the issue reported by https://github.com/strongloop-internal/scrum-cs/issues/352
=> Skip null values for length

lib/specgen/type-registry.js, test/specgen/schema-builder.test.js
Fix https://github.com/strongloop/loopback-component-explorer/issues/126
Signed-off-by: Clark Wang <clark.wangs@gmail.com>
=> map ObjectID to string type

lib/specgen/swagger-spec-generator.js
Signed-off-by: Candy Ng ngcandy@ca.ibm.com
=> Fix typo in comment.

lib/specgen/type-registry.js, test/specgen/schema-builder.test.js
Fix https://github.com/strongloop/loopback-component-explorer/issues/136
@bajtos  Please review.
=> Add GeoPoint support to explorer.

lib/codegen/json-schema.js, test/codegen/pet-expanded.json
A follow-up for #15, fixes #14
=> Fix handling of allOf when generating models

lib/specgen/model-helper.js, lib/specgen/type-registry.js, test/specgen/swagger-spec-generator.test.js
Connect to strongloop/loopback-component-explorer#143
=> Exclude definitions that are not referenced

lib/specgen/model-helper.js, lib/specgen/type-registry.js, test/specgen/schema-builder.test.js
Connect to https://github.com/strongloop/loopback/issues/1842
=> Make type geopoint case insensitive

example/pet-store-2.0.json, lib/codegen/generator-v2.js
/to @bajtos 
See https://github.com/strongloop/strongloop/issues/299
=> Handle extensions under paths

lib/specgen/route-helper.js, test/specgen/route-helper.test.js
Connect to https://github.com/strongloop/loopback-component-explorer/issues/105
=> Support default status codes

lib/specgen/model-helper.js, test/specgen/model-helper.test.js
Connect to strongloop-internal/scrum-loopback#898
=> Add custom definition to swagger file

lib/specgen/swagger-spec-generator.js, test/specgen/model-helper.test.js, test/specgen/swagger-spec-generator.test.js
Connect to strongloop-internal/scrum-loopback#900
Pick up `swagger` from server/config.json
```
...
"swagger": {
"info": {
"x-ibm-name": "my APIC app"
},
"x-ibm-configuration": {
"testable": true,
"etc.": "etc."
}
}
``` 
Created swagger file:
The swagger file could not update due to this bug https://github.ibm.com/apimesh/scrum-platform-foundation/issues/1141
=> Add doc root

test/specgen/swagger-spec-generator.test.js
* Add `patch` verb in test
/to: @bajtos @davidcheung
=> Add `patch` verb in test

package.json
Created a `loopback-2.x` branch; however I do not have admin access to make it protected; @superkhau I assume you have the permission; could you please make it protected? Thanks!
/to: @superkhau
=> Use juggler@3 and loopback@3 for testing

lib/specgen/route-helper.js, test/specgen/swagger-spec-generator.test.js
* Adjust route parameters sequence
Connect to https://github.com/strongloop/loopback-swagger/pull/66
/to: @bajtos @taoyuan @strongloop/squad-epitome PTAL. Thanks!
=> Adjust route parameters sequence

lib/codegen/model.ejs, package.json
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/npm:ejs:20161130
- https://snyk.io/vuln/npm:ejs:20161130-1
- https://snyk.io/vuln/npm:ejs:20161128
Latest report for strongloop/loopback-swagger:
https://snyk.io/test/github/strongloop/loopback-swagger
- Backport #76
=> fix: package.json to reduce vulnerabilities

lib/specgen/type-registry.js, test/specgen/schema-builder.test.js
https://github.com/strongloop/loopback-datasource-juggler/pull/1356
https://github.com/strongloop/loopback-connector-mysql/issues/149
=> type-registry: add DateString type

package.json
=> Update eslint config to the latest

example/specs/1.2/pet.json, example/specs/1.2/store.json, example/specs/1.2/user.json
To fix #75 by adding store.json. Also fixed basePath in user.json, pet.json
- connect to #75 
=> Fix basePath in user.json & pet.json, add store.json

.npmrc, .travis.yml, lib/codegen/generator-v1.2.js, lib/specgen/route-helper.js, lib/specgen/swagger-spec-generator.js, package.json, test/codegen/swagger-v2.test.js, test/specgen/schema-builder.test.js, test/specgen/swagger-spec-generator.test.js
- Drop support for Node.js 4.x
- Travis: add Node.js 8.x and 10.x
- Update strong-globalize and debug to latest
- Update eslint + config to latest
- Disable package-lock feature of npm
- Update mocha & chai to latest
=> Drop support for Node.js 4.x + update dependencies

example/generator.js, index.js, lib/codegen/generator-base.js, lib/codegen/generator-v1.2.js, lib/codegen/generator-v2.js, lib/codegen/json-schema.js, lib/codegen/model-template.js, lib/codegen/spec-converter.js, lib/specgen/model-helper.js, lib/specgen/route-helper.js, lib/specgen/schema-builder.js, lib/specgen/swagger-spec-generator.js, lib/specgen/tag-builder.js, lib/specgen/type-registry.js, package.json, test/codegen/json-schema.test.js, test/codegen/swagger-v2.test.js, test/specgen/fixtures/dummy-swagger-ui/swagger-ui.js, test/specgen/model-helper.test.js, test/specgen/route-helper.test.js, test/specgen/schema-builder.test.js, test/specgen/swagger-spec-generator.test.js, test/specgen/tag-builder.test.js
- connect to https://github.com/strongloop-internal/scrum-apex/issues/406
=> chore: update copyrights years
